os: osx
language: swift
osx_image: xcode11.4
before_install:
    - brew update
    - brew install xctool
script: xcodebuild -project covid-mac.xcodeproj -scheme covid-mac build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO"
